using Microsoft.AspNetCore.Identity.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore;
using System.ComponentModel.DataAnnotations.Schema;
using UniAccomodation.Models;

namespace UniAccomodation.Data
{
    public class UniAccomodationDbContext : IdentityDbContext<ApplicationUser>
    {
        public DbSet<Advert> Adverts { get; set; }
        public DbSet<Landlord> Landlords { get; set; }
        public DbSet<AccomodationOfficer> AccomodationOfficers { get; set; }
        public DbSet<ApplicationUser> ApplicationUsers { get; set; }

        public UniAccomodationDbContext(DbContextOptions<UniAccomodationDbContext> options) 
            : base(options)
        {
        }

        protected override void OnModelCreating(ModelBuilder modelBuilder)
        {
            // Identity OnModelCreating
            base.OnModelCreating(modelBuilder);

            modelBuilder.Entity<ApplicationUser>()
                // Alternate key to reference from other entities (relationships)
                .HasAlternateKey("ApplicationId")
                // Auto-generated by database (auto-increment)
                .HasAnnotation("DatabaseGenerated", DatabaseGeneratedOption.Identity);

            modelBuilder.Entity<Landlord>()
                // Landlord has N adverts
                .HasMany(landl => landl.Adverts)
                // Advert has 1 landlord
                .WithOne(adv => adv.Landlord);

            modelBuilder.Entity<Advert>()
                .ToTable("Advert")
                // Advert has 1 landlord
                .HasOne(adv => adv.Landlord)
                // Landlord has N adverts
                .WithMany(landl => landl.Adverts)
                .HasForeignKey("LandlordId")
                // Foreign key points to the int ID we created in ApplicationUser entity
                .HasPrincipalKey(l => l.ApplicationId);

            modelBuilder.Entity<Advert>()
                // Advert has 1 officer (that aproves/rejects it)
                .HasOne(adv => adv.Officer)
                // Officer can review N adverts, but navigation property does not exist
                .WithMany()
                .HasForeignKey("OfficerId")
                // Foreign key points to the int ID we created in ApplicationUser entity
                .HasPrincipalKey(off => off.ApplicationId)
                // Advert may have 0 officers related
                // (when advert is created it is not aproved not rejected, it is pending)
                // Note: this is redundant since we made the foreign key nullable
                .IsRequired(false);
        } 
    }
}
